# Generated by Django 2.2 on 2019-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hyderabad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('company', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('eligibility', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=20)),
            ],
        ),
    ]
